name: easy_books
description: EasyBooks Sales and Stock Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2022.01.05+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2

  intl: ^0.20.2
  responsive_builder: ^0.7.1
  url_launcher: ^6.0.20
  intl_phone_field: ^3.0.1
  permission_handler: ^12.0.1
  file_picker: ^10.3.9
  flutter_file_dialog: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner: ^2.4.7
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/